Issue#13 Open api parent module skeleton
ITA-Dnipro/Java-Home-Project-CQRS-Javelin pull request #17
Opened 2022-05-19 15:08 UTC by Pavlo-Ponomarenko

dev
## GitHub

* [GitHub issue](https://github.com/ITA-Dnipro/Java-Home-Project-CQRS-Javelin/issues/7)

## Summary of issue

Implementing open api parent module skeleton
## Summary of change

Open api module generation. Requests for news implementation

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-05-19 15:13 UTC, vladyslavyarets commented on open-api/src/main/resources/yaml/models/common.yaml
> +      example: 1
Please, add empty final line. That's basic GitHub requirement.

2022-05-19 15:13 UTC, vladyslavyarets commented on open-api/src/main/resources/yaml/openapi.yaml
> +    $ref: './paths/news.yaml#/news-newsId'
Please, add empty final line. That's basic GitHub requirement.

2022-05-19 15:15 UTC, vladyslavyarets commented on open-api/src/main/resources/yaml/openapi.yaml
> +  title: Java-Home-Project-CQRS-Javelin-reader
This open-api inplementation will be common for few modules, so you no need to specify reader module here.

2022-05-19 15:15 UTC, vladyslavyarets commented on open-api/src/main/resources/yaml/parameters/parameters.yaml
> +  description: The title of the News
Please, add empty final line. That's basic GitHub requirement.

2022-05-19 15:18 UTC, vladyslavyarets commented on open-api/src/main/resources/yaml/responses/responses.yaml
> +          $ref: '../models/news.yaml#/ReadNews'
Please, add empty final line. That's basic GitHub requirement.

2022-05-19 15:19 UTC, vladyslavyarets requested changes

2022-05-19 15:19 UTC, vladyslavyarets commented on open-api/src/main/resources/yaml/openapi.yaml
> +  title: Java-Home-Project-CQRS-Javelin-reader
This open-api inplementation will be common for few modules, so you no need to specify reader module here.

2022-05-20 14:17 UTC, vladyslavyarets approved these changes

2022-05-20 14:18 UTC, gendalf-fx approved these changes

2022-05-20 14:21 UTC, merged